
CREDDIT_CFLAGS:=$(PROJCFLAGS)
CREDDIT_LDFLAGS:=-lncurses `curl-config --cflags` `curl-config --libs` -L$(BUILD_DIR) -lreddit

EXECUTABLE_NAME:=creddit
CREDDIT_DIR_CMP:=$(BUILD_DIR)/src
CREDDIT_DIR:=src

EXECUTABLE_FULL:=$(BUILD_DIR)/$(EXECUTABLE_NAME)

COMPILE_TARGETS+=$(EXECUTABLE_FULL)
CLEAN_TARGETS+=creddit_clean
INSTALL_TARGETS+=creddit_install

CREDDIT_SOURCES:=$(patsubst $(CREDDIT_DIR)/%,%,$(wildcard $(CREDDIT_DIR)/*.c))
CREDDIT_OBJECTS:=$(patsubst %,$(CREDDIT_DIR_CMP)/%,$(CREDDIT_SOURCES:.c=.o))

$(CREDDIT_DIR_CMP): | $(BUILD_DIR)
	$(QUIETLY)$(ECHO) " MKDIR $(CREDDIT_DIR_CMP)"
	$(QUIETLY)$(MKDIR) $(CREDDIT_DIR_CMP)

creddit: $(EXECUTABLE_FULL)

$(EXECUTABLE_FULL): libreddit $(CREDDIT_OBJECTS) | $(CREDDIT_DIR_CMP)
	$(QUIETLY)$(ECHO) " CC $(EXECUTABLE_FULL)"
	$(QUIETLY)$(CC) $(CREDDIT_OBJECTS) $(CREDDIT_CFLAGS) $(CREDDIT_LDFLAGS) -o $(EXECUTABLE_FULL)

creddit_clean:
	$(QUIETLY)$(ECHO) " RM $(CREDDIT_DIR_CMP)"
	$(QUIETLY)$(RM) -fr $(CREDDIT_DIR_CMP)

creddit_install: $(EXECUTABLE_FULL)
	$(QUIETLY)$(ECHO) " INSTALL $(EXECUTABLE_FULL)"
	$(QUIETLY)$(INSTALL) -m 0755 $(EXECUTABLE_FULL) $(PREFIX)/bin/

$(CREDDIT_DIR_CMP)/%.o: $(CREDDIT_DIR)/%.c | $(CREDDIT_DIR_CMP)
	$(QUIETLY)$(ECHO) " CC $@"
	$(QUIETLY)$(CC) $(CREDDIT_CFLAGS) -c $< -o $@
